import { z } from 'zod';

// Affiliate provider enum matching the DB CHECK constraint
export const AffiliateProviderSchema = z.enum(['booking_com', 'agoda']);
export type AffiliateProvider = z.infer<typeof AffiliateProviderSchema>;

// Schema for a single hotel extracted from a search result page
export const ExtractedHotelSchema = z.object({
  hotel_name: z.string().min(1),
  hotel_address: z.string().nullable().optional(),
  latitude: z.number().nullable().optional(),
  longitude: z.number().nullable().optional(),
  price_per_night_min: z.number().positive().nullable().optional(),
  currency: z.string().length(3).default('USD'),
  rating: z.number().min(0).max(10).nullable().optional(),
  review_count: z.number().int().min(0).default(0),
  affiliate_provider: AffiliateProviderSchema,
  affiliate_url: z.string().url(),
  affiliate_id: z.string().nullable().optional(),
  image_url: z.string().url().nullable().optional(),
  amenities: z.array(z.string()).default([]),
  // Computed after extraction using haversine
  distance_from_event_meters: z.number().int().nullable().optional(),
});

export type ExtractedHotel = z.infer<typeof ExtractedHotelSchema>;

// Shape of an event row returned from getEventsWithoutHotels
export interface EventForEnrichment {
  id: string;
  title: string;
  venue_name: string | null;
  address: string | null;
  city: string;
  country_code: string;
  latitude: number;
  longitude: number;
  start_datetime: Date;
}

// Summary returned by enrichEventWithHotels
export interface HotelEnrichmentResult {
  eventId: string;
  eventTitle: string;
  hotelsFound: number;
  hotelsUpserted: number;
  errors: string[];
  durationMs: number;
}

// Directions and transit info generated by Claude for an event venue
export interface DirectionsInfo {
  // Plain-English summary of how to get to the venue
  summary: string;
  // Nearest public transit options (metro, bus, tram)
  transitOptions: TransitOption[];
  // Estimated walking time from the nearest metro/bus stop (minutes)
  walkingTimeFromTransitMinutes: number | null;
  // Estimated driving time from the city center (minutes)
  drivingTimeFromCenterMinutes: number | null;
  // Parking notes if applicable
  parkingNotes: string | null;
  // Language of the directions (ISO 639-1)
  language: string;
}

export interface TransitOption {
  type: 'metro' | 'bus' | 'tram' | 'train' | 'ferry' | 'other';
  line: string;       // e.g. "Line 2", "Route 45"
  stopName: string;   // Name of the nearest stop
  walkingMinutes: number;
}

// Full result of enrichAllEvents
export interface EnrichmentSummary {
  eventsProcessed: number;
  eventsSucceeded: number;
  eventsFailed: number;
  totalHotelsUpserted: number;
  durationMs: number;
  errors: string[];
}
